version: '3.8'
services:
  app:
    image: ${APP_IMAGE}
    # 만약 이미지를 미리 빌드한다면 build: . 를 제거할 수 있습니다.
    build: .
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    env_file:
      - .env
    depends_on:
      - mysql